---
- hosts: flask-docker
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
        update_cache: yes
    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: Build Docker Image
      command: docker build -t sukanya996/flask-app:latest 
        
    - name: Run Docker Container
      command: docker run -d -p 5000:5000 --name flask-app-container sukanya996/flask-app:latest
