---
- hosts: flask-docker
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present
        update_cache: yes

    - name: Add Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Pull Docker Image from Docker Hub
      command: docker pull sukanya996/flask-app:latest
      
    - name: Run Docker Container
      command: docker run -d --restart always -p 5000:5000 --name flask1 sukanya996/flask-app:latest 
